#!/bin/bash

#######################################
# Variables                           #
#######################################

SSD_DEVICE=$1

ON_TIME_TAG="Power_On_Hours"
WEAR_COUNT_TAG="Wear_Leveling_Count"
LBAS_WRITTEN_TAG="Total_LBAs_Written"
LBA_SIZE=512 # Value in bytes


BYTES_PER_MB=1048576
BYTES_PER_GB=1073741824
BYTES_PER_TB=1099511627776

#######################################
# Get total data written...           #
#######################################
# Lifetime_Writes_GiB, Total_LBAs_Written , Host_Writes_32MiB
# Get SMART attributes
SMART_INFO=$(sudo /usr/sbin/smartctl -A "$SSD_DEVICE")

# Extract required attributes
ON_TIME=$(echo "$SMART_INFO" | grep "$ON_TIME_TAG" | awk '{print $10}')
WEAR_COUNT=$(echo "$SMART_INFO" | grep "$WEAR_COUNT_TAG" | awk '{print $4}' | sed 's/^0*//')
LBAS_WRITTEN=$(echo "$SMART_INFO" | grep "$LBAS_WRITTEN_TAG" | awk '{print $10}')
Lifetime_Writes_GiB=$(echo "$SMART_INFO" | grep "Lifetime_Writes_GiB" | awk '{print $10}')
Host_Writes_32MiB=$(echo "$SMART_INFO" | grep "Host_Writes_32MiB" | awk '{print $10}')
Host_Writes=$(echo "$SMART_INFO" | grep "Host_Writes" | awk '{print $10}')

# Convert LBAs -> bytes
BYTES_WRITTEN=$(echo "$LBAS_WRITTEN * $LBA_SIZE" | bc)
MB_WRITTEN=$(echo "scale=3; $BYTES_WRITTEN / $BYTES_PER_MB" | bc)
GB_WRITTEN=$(echo "scale=3; $BYTES_WRITTEN / $BYTES_PER_GB" | bc)
#lba
hw_bytes_lba=$(echo "scale=3; $Host_Writes * $LBA_SIZE " | bc)
TB_WRITTEN=$(echo "scale=3; $BYTES_WRITTEN / $BYTES_PER_TB" | bc)
TB_WRITTEN_hw_lba=$(echo "scale=3; $hw_bytes_lba / $BYTES_PER_TB" | bc)

hw_bytes=$(echo "scale=3; $Host_Writes_32MiB * $BYTES_PER_GB * 32 " | bc)

TB_WRITTEN_ltw=$(echo "scale=3; $Lifetime_Writes_GiB / 1000" | bc)
TB_WRITTEN_hw=$(echo "scale=3; $hw_bytes / $BYTES_PER_TB" | bc)

# Output results...
echo "------------------------------"
echo " SSD Status:   $SSD_DEVICE"
echo "------------------------------"
echo " On time:      $(echo $ON_TIME | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta') hr"
echo "------------------------------"
echo " Data written:"
echo "           MBW: $(echo $MB_WRITTEN | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"
echo "           GBW: $(echo $GB_WRITTEN | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"
echo "           TBW: $(echo $TB_WRITTEN | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"
echo "           TBW: $(echo $TB_WRITTEN_ltw | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"
echo "           TBW: $(echo $TB_WRITTEN_hw | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"
#echo "           TB: $(echo $TB_WRITTEN_hw_lba | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"
echo "------------------------------"
echo " Mean write rate:"
echo "        MB/hr: $(echo "scale=3; $MB_WRITTEN / $ON_TIME" | bc | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"
echo "------------------------------"
echo " Drive health: ${WEAR_COUNT} %"
echo "------------------------------"


#echo "GB Written: $(echo "scale=3; $(sudo /usr/sbin/smartctl -A /dev/sda | grep "Total_LBAs_Written" | awk '{print $10}') * 512 / 1073741824" | bc | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"


